from pathlib import Path
p=Path('F:/game/MythicVFXLab/Source/MythicVFXLab/FrostMageGameplay.cpp');s=p.read_text()
s=s.replace('void AFMFrostMonster::ReceiveFire(float Damage){ApplySpellDamage(Damage);}','void AFMFrostMonster::ReceiveFire(float Damage){ApplySpellDamage(Damage);}\nvoid AFMFrostMonster::ReceiveArcane(float Damage){ApplySpellDamage(Damage);}')
s=s.replace(' BoltAnimation=FM::Asset<UAnimSequence>', ' ArcaneChannelSystem=FM::Asset<UNiagaraSystem>(TEXT("/Game/ArcaneMage/Niagara/NS_AM_Channel"));\n BoltAnimation=FM::Asset<UAnimSequence>',1)
s=s.replace('ClearFirePreview();FireCastTarget=nullptr;PlayPose','ClearFirePreview();FireCastTarget=nullptr;ArcaneTarget=nullptr;PlayPose')
s=s.replace('CastingSpell==1||CastingSpell==5||CastingSpell==7','CastingSpell==1||CastingSpell==5||CastingSpell==7||CastingSpell==8')
s=s.replace(' if(Spell>=5){ReleaseFireSpell(Spell);return;}',' if(Spell==8){ArcaneTarget=nullptr;Recovery=.3f;Message(TEXT("Arcane Missiles  /  5 bolts  /  45 damage"));UE_LOG(LogTemp,Display,TEXT("AM_CHANNEL_COMPLETE Shots=%d"),ArcaneShotsFired);return;}\n if(Spell>=5){ReleaseFireSpell(Spell);return;}')
s=s.replace(' FireballCooldown=FMath::Max',' ArcaneCooldown=FMath::Max(0.f,ArcaneCooldown-D);\n FireballCooldown=FMath::Max')
s=s.replace(' if(CastingSpell){const auto* PC=', ' if(CastingSpell==8)TickArcaneChannel(D);\n if(CastingSpell){const auto* PC=')
s=s.replace('CastingSpell==1&&IsValid(Target)', '(CastingSpell==1||CastingSpell==5||CastingSpell==8)&&IsValid(Target)')
s=s.replace(' InputComponent->BindKey(EKeys::Four,',' InputComponent->BindKey(EKeys::Eight,IE_Pressed,this,&AFMPlayerController::FMTestArcane);\n InputComponent->BindKey(EKeys::Four,')
s=s.replace('W<1150?4:7','W<1280?4:8').replace('for(int i=0;i<7;i++)','for(int i=0;i<8;i++)')
s=s.replace('TEXT("FLAMESTRIKE")};','TEXT("FLAMESTRIKE"),TEXT("ARCANE MISSILES")};')
s=s.replace('TEXT("AoE + burn / 2s")};','TEXT("AoE + burn / 2s"),TEXT("5 bolts / Channel")};')
s=s.replace('P->FireBlastCooldown,P->FlamestrikeCooldown};','P->FireBlastCooldown,P->FlamestrikeCooldown,P->ArcaneCooldown};').replace('8.f,.5f,8.f,10.f};','8.f,.5f,8.f,10.f,4.f};')
s=s.replace('const FLinearColor Accent=i>=4?', 'const FLinearColor Accent=i==7?FLinearColor(.64f,.28f,1.f):(i>=4?')
s=s.replace('FLinearColor(.19f,.49f,.72f)));','FLinearColor(.19f,.49f,.72f))));')
s=s.replace('const FLinearColor Tint=P->CastingSpell>=5?', 'const FLinearColor Tint=P->CastingSpell==8?FLinearColor(.48f,.15f,.95f,.9f):(P->CastingSpell>=5?')
s=s.replace('FLinearColor(.17f,.56f,.88f,.9f));','FLinearColor(.17f,.56f,.88f,.9f)));')
s=s.replace('366*(1-P->CastRemaining/FMath::Max(.01f,P->CastDuration))','366*(P->CastingSpell==8?P->CastRemaining/FMath::Max(.01f,P->CastDuration):1-P->CastRemaining/FMath::Max(.01f,P->CastDuration))')
s=s.replace('TEXT("Calling Flamestrike...")};','TEXT("Calling Flamestrike..."),TEXT("Channeling Arcane Missiles...")};').replace('FMath::Clamp(P->CastingSpell,0,7)','FMath::Clamp(P->CastingSpell,0,8)')
s=s.replace(' |  7 Flamestrike"',' |  7 Flamestrike  |  8 Arcane"')
p.write_text(s)
